package com.deck;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

// class cards 
/**
 * with members suite of cards to store card rank and card suite in a single
 * object
 * ranks is static member used to create suite of cards
 * suite is also a static member to create suite of cards
 */
public class Cards {
    List<NodeForCard> suitOfCards;
    static String[] ranks={"2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King", "Ace"};
    static String[] suite={"Clubs","Diamonds","Hearts","Spades"};

    //constructor to set the member of card collection  
    public Cards(){
        suitOfCards=new ArrayList<>();
    }

    /**
     * method initilizeSuitOfCards intilizes suite of cards with its properties
     * here we iterate through ranks for every suite and create object of 
     * NodeForCards and the we add it to the list suit of cards
     */
    public void initilizeSuitOfCards(){
        for(int i=0;i<suite.length;i++){
            for(int j=0;j<ranks.length;j++){
                this.suitOfCards.add(new NodeForCard(suite[i], ranks[j]));
            }
        }
    }

    /**
     * method shuffle is  used to shuffle the cards 
     * here we shuffle the cards using random index generated by math.random
     * and then we swap it using Colletions.sort method with the index 0
     */
    public void shuffle(){
        for(NodeForCard nd:suitOfCards){
            int randomIndex=(int) (Math.floor(Math.random()*52)%52);
            Collections.swap(this.suitOfCards, 0, randomIndex);
        }
    }
}
